name: ohif/deploy-v3

on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    container:
      image: node:20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      
      - name: Clone and install OHIF dependencies
        run: |
          git clone https://github.com/ImagingDataCommons/ViewersV3.git
          cd ViewersV3
          yarn install --frozen-lockfile

      - name: Build OHIF
        run: |
          cd ViewersV3
          wget -O ./firebase.json "${{ vars.OHIF_FIREBASE_JSON_URL }}"
          wget -O ./platform/app/public/config/test.js "${{ vars.OHIF_CONFIG_JS_URL }}"
          PUBLIC_URL=/ APP_CONFIG=config/test.js yarn build

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0.7.1
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          expires: 30d
          projectId: viewers-sandbox-gha-testing
          entryPoint: ./ViewersV3
          channelId: live 
          # channelId: # 'pr-${{ github.event.number }}-${{ github.event.pull_request.head.ref }}'